// Code generated by MockGen. DO NOT EDIT.
// Source: internal/teleport/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/teleport/service.go -destination=internal/teleport/mocks/mock_api.go -package=mocks API
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/gravitational/teleport/api/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// GetAccessCapabilities mocks base method.
func (m *MockAPI) GetAccessCapabilities(ctx context.Context, req types.AccessCapabilitiesRequest) (*types.AccessCapabilities, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessCapabilities", ctx, req)
	ret0, _ := ret[0].(*types.AccessCapabilities)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessCapabilities indicates an expected call of GetAccessCapabilities.
func (mr *MockAPIMockRecorder) GetAccessCapabilities(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessCapabilities", reflect.TypeOf((*MockAPI)(nil).GetAccessCapabilities), ctx, req)
}

// GetUsers mocks base method.
func (m *MockAPI) GetUsers(ctx context.Context, withSecrets bool) ([]types.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx, withSecrets)
	ret0, _ := ret[0].([]types.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockAPIMockRecorder) GetUsers(ctx, withSecrets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockAPI)(nil).GetUsers), ctx, withSecrets)
}
