// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gravitational/teleport/api/types (interfaces: User)
//
// Generated by this command:
//
//	mockgen github.com/gravitational/teleport/api/types User
//

// Package mock_types is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	types "github.com/gravitational/teleport/api/types"
	gomock "go.uber.org/mock/gomock"
)

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
	isgomock struct{}
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// AddRole mocks base method.
func (m *MockUser) AddRole(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddRole", name)
}

// AddRole indicates an expected call of AddRole.
func (mr *MockUserMockRecorder) AddRole(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRole", reflect.TypeOf((*MockUser)(nil).AddRole), name)
}

// BotGenerationLabel mocks base method.
func (m *MockUser) BotGenerationLabel() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotGenerationLabel")
	ret0, _ := ret[0].(string)
	return ret0
}

// BotGenerationLabel indicates an expected call of BotGenerationLabel.
func (mr *MockUserMockRecorder) BotGenerationLabel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotGenerationLabel", reflect.TypeOf((*MockUser)(nil).BotGenerationLabel))
}

// Clone mocks base method.
func (m *MockUser) Clone() types.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone")
	ret0, _ := ret[0].(types.User)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockUserMockRecorder) Clone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockUser)(nil).Clone))
}

// Expiry mocks base method.
func (m *MockUser) Expiry() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expiry")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Expiry indicates an expected call of Expiry.
func (mr *MockUserMockRecorder) Expiry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expiry", reflect.TypeOf((*MockUser)(nil).Expiry))
}

// GetAWSRoleARNs mocks base method.
func (m *MockUser) GetAWSRoleARNs() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAWSRoleARNs")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAWSRoleARNs indicates an expected call of GetAWSRoleARNs.
func (mr *MockUserMockRecorder) GetAWSRoleARNs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAWSRoleARNs", reflect.TypeOf((*MockUser)(nil).GetAWSRoleARNs))
}

// GetAllLabels mocks base method.
func (m *MockUser) GetAllLabels() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLabels")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetAllLabels indicates an expected call of GetAllLabels.
func (mr *MockUserMockRecorder) GetAllLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLabels", reflect.TypeOf((*MockUser)(nil).GetAllLabels))
}

// GetAzureIdentities mocks base method.
func (m *MockUser) GetAzureIdentities() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAzureIdentities")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAzureIdentities indicates an expected call of GetAzureIdentities.
func (mr *MockUserMockRecorder) GetAzureIdentities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAzureIdentities", reflect.TypeOf((*MockUser)(nil).GetAzureIdentities))
}

// GetCreatedBy mocks base method.
func (m *MockUser) GetCreatedBy() types.CreatedBy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreatedBy")
	ret0, _ := ret[0].(types.CreatedBy)
	return ret0
}

// GetCreatedBy indicates an expected call of GetCreatedBy.
func (mr *MockUserMockRecorder) GetCreatedBy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreatedBy", reflect.TypeOf((*MockUser)(nil).GetCreatedBy))
}

// GetDatabaseNames mocks base method.
func (m *MockUser) GetDatabaseNames() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseNames")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetDatabaseNames indicates an expected call of GetDatabaseNames.
func (mr *MockUserMockRecorder) GetDatabaseNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseNames", reflect.TypeOf((*MockUser)(nil).GetDatabaseNames))
}

// GetDatabaseUsers mocks base method.
func (m *MockUser) GetDatabaseUsers() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseUsers")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetDatabaseUsers indicates an expected call of GetDatabaseUsers.
func (mr *MockUserMockRecorder) GetDatabaseUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseUsers", reflect.TypeOf((*MockUser)(nil).GetDatabaseUsers))
}

// GetGCPServiceAccounts mocks base method.
func (m *MockUser) GetGCPServiceAccounts() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGCPServiceAccounts")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetGCPServiceAccounts indicates an expected call of GetGCPServiceAccounts.
func (mr *MockUserMockRecorder) GetGCPServiceAccounts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGCPServiceAccounts", reflect.TypeOf((*MockUser)(nil).GetGCPServiceAccounts))
}

// GetGithubIdentities mocks base method.
func (m *MockUser) GetGithubIdentities() []types.ExternalIdentity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGithubIdentities")
	ret0, _ := ret[0].([]types.ExternalIdentity)
	return ret0
}

// GetGithubIdentities indicates an expected call of GetGithubIdentities.
func (mr *MockUserMockRecorder) GetGithubIdentities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGithubIdentities", reflect.TypeOf((*MockUser)(nil).GetGithubIdentities))
}

// GetKind mocks base method.
func (m *MockUser) GetKind() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKind")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetKind indicates an expected call of GetKind.
func (mr *MockUserMockRecorder) GetKind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKind", reflect.TypeOf((*MockUser)(nil).GetKind))
}

// GetKubeGroups mocks base method.
func (m *MockUser) GetKubeGroups() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKubeGroups")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetKubeGroups indicates an expected call of GetKubeGroups.
func (mr *MockUserMockRecorder) GetKubeGroups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubeGroups", reflect.TypeOf((*MockUser)(nil).GetKubeGroups))
}

// GetKubeUsers mocks base method.
func (m *MockUser) GetKubeUsers() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKubeUsers")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetKubeUsers indicates an expected call of GetKubeUsers.
func (mr *MockUserMockRecorder) GetKubeUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubeUsers", reflect.TypeOf((*MockUser)(nil).GetKubeUsers))
}

// GetLabel mocks base method.
func (m *MockUser) GetLabel(key string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLabel", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetLabel indicates an expected call of GetLabel.
func (mr *MockUserMockRecorder) GetLabel(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabel", reflect.TypeOf((*MockUser)(nil).GetLabel), key)
}

// GetLocalAuth mocks base method.
func (m *MockUser) GetLocalAuth() *types.LocalAuthSecrets {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalAuth")
	ret0, _ := ret[0].(*types.LocalAuthSecrets)
	return ret0
}

// GetLocalAuth indicates an expected call of GetLocalAuth.
func (mr *MockUserMockRecorder) GetLocalAuth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalAuth", reflect.TypeOf((*MockUser)(nil).GetLocalAuth))
}

// GetLogins mocks base method.
func (m *MockUser) GetLogins() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogins")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetLogins indicates an expected call of GetLogins.
func (mr *MockUserMockRecorder) GetLogins() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogins", reflect.TypeOf((*MockUser)(nil).GetLogins))
}

// GetMetadata mocks base method.
func (m *MockUser) GetMetadata() types.Metadata {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata")
	ret0, _ := ret[0].(types.Metadata)
	return ret0
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockUserMockRecorder) GetMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockUser)(nil).GetMetadata))
}

// GetName mocks base method.
func (m *MockUser) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockUserMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockUser)(nil).GetName))
}

// GetOIDCIdentities mocks base method.
func (m *MockUser) GetOIDCIdentities() []types.ExternalIdentity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOIDCIdentities")
	ret0, _ := ret[0].([]types.ExternalIdentity)
	return ret0
}

// GetOIDCIdentities indicates an expected call of GetOIDCIdentities.
func (mr *MockUserMockRecorder) GetOIDCIdentities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOIDCIdentities", reflect.TypeOf((*MockUser)(nil).GetOIDCIdentities))
}

// GetPasswordState mocks base method.
func (m *MockUser) GetPasswordState() types.PasswordState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordState")
	ret0, _ := ret[0].(types.PasswordState)
	return ret0
}

// GetPasswordState indicates an expected call of GetPasswordState.
func (mr *MockUserMockRecorder) GetPasswordState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordState", reflect.TypeOf((*MockUser)(nil).GetPasswordState))
}

// GetRevision mocks base method.
func (m *MockUser) GetRevision() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevision")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRevision indicates an expected call of GetRevision.
func (mr *MockUserMockRecorder) GetRevision() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevision", reflect.TypeOf((*MockUser)(nil).GetRevision))
}

// GetRoles mocks base method.
func (m *MockUser) GetRoles() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoles")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetRoles indicates an expected call of GetRoles.
func (mr *MockUserMockRecorder) GetRoles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoles", reflect.TypeOf((*MockUser)(nil).GetRoles))
}

// GetSAMLIdentities mocks base method.
func (m *MockUser) GetSAMLIdentities() []types.ExternalIdentity {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSAMLIdentities")
	ret0, _ := ret[0].([]types.ExternalIdentity)
	return ret0
}

// GetSAMLIdentities indicates an expected call of GetSAMLIdentities.
func (mr *MockUserMockRecorder) GetSAMLIdentities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSAMLIdentities", reflect.TypeOf((*MockUser)(nil).GetSAMLIdentities))
}

// GetStaticLabels mocks base method.
func (m *MockUser) GetStaticLabels() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaticLabels")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetStaticLabels indicates an expected call of GetStaticLabels.
func (mr *MockUserMockRecorder) GetStaticLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaticLabels", reflect.TypeOf((*MockUser)(nil).GetStaticLabels))
}

// GetStatus mocks base method.
func (m *MockUser) GetStatus() types.LoginStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(types.LoginStatus)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockUserMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockUser)(nil).GetStatus))
}

// GetSubKind mocks base method.
func (m *MockUser) GetSubKind() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubKind")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSubKind indicates an expected call of GetSubKind.
func (mr *MockUserMockRecorder) GetSubKind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubKind", reflect.TypeOf((*MockUser)(nil).GetSubKind))
}

// GetTraits mocks base method.
func (m *MockUser) GetTraits() map[string][]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTraits")
	ret0, _ := ret[0].(map[string][]string)
	return ret0
}

// GetTraits indicates an expected call of GetTraits.
func (mr *MockUserMockRecorder) GetTraits() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTraits", reflect.TypeOf((*MockUser)(nil).GetTraits))
}

// GetTrustedDeviceIDs mocks base method.
func (m *MockUser) GetTrustedDeviceIDs() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrustedDeviceIDs")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetTrustedDeviceIDs indicates an expected call of GetTrustedDeviceIDs.
func (mr *MockUserMockRecorder) GetTrustedDeviceIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrustedDeviceIDs", reflect.TypeOf((*MockUser)(nil).GetTrustedDeviceIDs))
}

// GetUserType mocks base method.
func (m *MockUser) GetUserType() types.UserType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserType")
	ret0, _ := ret[0].(types.UserType)
	return ret0
}

// GetUserType indicates an expected call of GetUserType.
func (mr *MockUserMockRecorder) GetUserType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserType", reflect.TypeOf((*MockUser)(nil).GetUserType))
}

// GetVersion mocks base method.
func (m *MockUser) GetVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockUserMockRecorder) GetVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockUser)(nil).GetVersion))
}

// GetWeakestDevice mocks base method.
func (m *MockUser) GetWeakestDevice() types.MFADeviceKind {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeakestDevice")
	ret0, _ := ret[0].(types.MFADeviceKind)
	return ret0
}

// GetWeakestDevice indicates an expected call of GetWeakestDevice.
func (mr *MockUserMockRecorder) GetWeakestDevice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeakestDevice", reflect.TypeOf((*MockUser)(nil).GetWeakestDevice))
}

// GetWindowsLogins mocks base method.
func (m *MockUser) GetWindowsLogins() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWindowsLogins")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetWindowsLogins indicates an expected call of GetWindowsLogins.
func (mr *MockUserMockRecorder) GetWindowsLogins() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWindowsLogins", reflect.TypeOf((*MockUser)(nil).GetWindowsLogins))
}

// IsBot mocks base method.
func (m *MockUser) IsBot() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBot")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBot indicates an expected call of IsBot.
func (mr *MockUserMockRecorder) IsBot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBot", reflect.TypeOf((*MockUser)(nil).IsBot))
}

// MatchSearch mocks base method.
func (m *MockUser) MatchSearch(searchValues []string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchSearch", searchValues)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MatchSearch indicates an expected call of MatchSearch.
func (mr *MockUserMockRecorder) MatchSearch(searchValues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchSearch", reflect.TypeOf((*MockUser)(nil).MatchSearch), searchValues)
}

// Origin mocks base method.
func (m *MockUser) Origin() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Origin")
	ret0, _ := ret[0].(string)
	return ret0
}

// Origin indicates an expected call of Origin.
func (mr *MockUserMockRecorder) Origin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Origin", reflect.TypeOf((*MockUser)(nil).Origin))
}

// ResetLocks mocks base method.
func (m *MockUser) ResetLocks() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetLocks")
}

// ResetLocks indicates an expected call of ResetLocks.
func (mr *MockUserMockRecorder) ResetLocks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetLocks", reflect.TypeOf((*MockUser)(nil).ResetLocks))
}

// SetAWSRoleARNs mocks base method.
func (m *MockUser) SetAWSRoleARNs(awsRoleARNs []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAWSRoleARNs", awsRoleARNs)
}

// SetAWSRoleARNs indicates an expected call of SetAWSRoleARNs.
func (mr *MockUserMockRecorder) SetAWSRoleARNs(awsRoleARNs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAWSRoleARNs", reflect.TypeOf((*MockUser)(nil).SetAWSRoleARNs), awsRoleARNs)
}

// SetAzureIdentities mocks base method.
func (m *MockUser) SetAzureIdentities(azureIdentities []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAzureIdentities", azureIdentities)
}

// SetAzureIdentities indicates an expected call of SetAzureIdentities.
func (mr *MockUserMockRecorder) SetAzureIdentities(azureIdentities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAzureIdentities", reflect.TypeOf((*MockUser)(nil).SetAzureIdentities), azureIdentities)
}

// SetCreatedBy mocks base method.
func (m *MockUser) SetCreatedBy(arg0 types.CreatedBy) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCreatedBy", arg0)
}

// SetCreatedBy indicates an expected call of SetCreatedBy.
func (mr *MockUserMockRecorder) SetCreatedBy(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCreatedBy", reflect.TypeOf((*MockUser)(nil).SetCreatedBy), arg0)
}

// SetDatabaseNames mocks base method.
func (m *MockUser) SetDatabaseNames(databaseNames []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDatabaseNames", databaseNames)
}

// SetDatabaseNames indicates an expected call of SetDatabaseNames.
func (mr *MockUserMockRecorder) SetDatabaseNames(databaseNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDatabaseNames", reflect.TypeOf((*MockUser)(nil).SetDatabaseNames), databaseNames)
}

// SetDatabaseRoles mocks base method.
func (m *MockUser) SetDatabaseRoles(databaseRoles []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDatabaseRoles", databaseRoles)
}

// SetDatabaseRoles indicates an expected call of SetDatabaseRoles.
func (mr *MockUserMockRecorder) SetDatabaseRoles(databaseRoles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDatabaseRoles", reflect.TypeOf((*MockUser)(nil).SetDatabaseRoles), databaseRoles)
}

// SetDatabaseUsers mocks base method.
func (m *MockUser) SetDatabaseUsers(databaseUsers []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDatabaseUsers", databaseUsers)
}

// SetDatabaseUsers indicates an expected call of SetDatabaseUsers.
func (mr *MockUserMockRecorder) SetDatabaseUsers(databaseUsers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDatabaseUsers", reflect.TypeOf((*MockUser)(nil).SetDatabaseUsers), databaseUsers)
}

// SetExpiry mocks base method.
func (m *MockUser) SetExpiry(arg0 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetExpiry", arg0)
}

// SetExpiry indicates an expected call of SetExpiry.
func (mr *MockUserMockRecorder) SetExpiry(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExpiry", reflect.TypeOf((*MockUser)(nil).SetExpiry), arg0)
}

// SetGCPServiceAccounts mocks base method.
func (m *MockUser) SetGCPServiceAccounts(accounts []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGCPServiceAccounts", accounts)
}

// SetGCPServiceAccounts indicates an expected call of SetGCPServiceAccounts.
func (mr *MockUserMockRecorder) SetGCPServiceAccounts(accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGCPServiceAccounts", reflect.TypeOf((*MockUser)(nil).SetGCPServiceAccounts), accounts)
}

// SetGithubIdentities mocks base method.
func (m *MockUser) SetGithubIdentities(arg0 []types.ExternalIdentity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGithubIdentities", arg0)
}

// SetGithubIdentities indicates an expected call of SetGithubIdentities.
func (mr *MockUserMockRecorder) SetGithubIdentities(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGithubIdentities", reflect.TypeOf((*MockUser)(nil).SetGithubIdentities), arg0)
}

// SetHostUserGID mocks base method.
func (m *MockUser) SetHostUserGID(gid string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHostUserGID", gid)
}

// SetHostUserGID indicates an expected call of SetHostUserGID.
func (mr *MockUserMockRecorder) SetHostUserGID(gid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHostUserGID", reflect.TypeOf((*MockUser)(nil).SetHostUserGID), gid)
}

// SetHostUserUID mocks base method.
func (m *MockUser) SetHostUserUID(uid string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHostUserUID", uid)
}

// SetHostUserUID indicates an expected call of SetHostUserUID.
func (mr *MockUserMockRecorder) SetHostUserUID(uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHostUserUID", reflect.TypeOf((*MockUser)(nil).SetHostUserUID), uid)
}

// SetKubeGroups mocks base method.
func (m *MockUser) SetKubeGroups(kubeGroups []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetKubeGroups", kubeGroups)
}

// SetKubeGroups indicates an expected call of SetKubeGroups.
func (mr *MockUserMockRecorder) SetKubeGroups(kubeGroups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKubeGroups", reflect.TypeOf((*MockUser)(nil).SetKubeGroups), kubeGroups)
}

// SetKubeUsers mocks base method.
func (m *MockUser) SetKubeUsers(kubeUsers []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetKubeUsers", kubeUsers)
}

// SetKubeUsers indicates an expected call of SetKubeUsers.
func (mr *MockUserMockRecorder) SetKubeUsers(kubeUsers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKubeUsers", reflect.TypeOf((*MockUser)(nil).SetKubeUsers), kubeUsers)
}

// SetLocalAuth mocks base method.
func (m *MockUser) SetLocalAuth(auth *types.LocalAuthSecrets) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLocalAuth", auth)
}

// SetLocalAuth indicates an expected call of SetLocalAuth.
func (mr *MockUserMockRecorder) SetLocalAuth(auth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLocalAuth", reflect.TypeOf((*MockUser)(nil).SetLocalAuth), auth)
}

// SetLocked mocks base method.
func (m *MockUser) SetLocked(until time.Time, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLocked", until, reason)
}

// SetLocked indicates an expected call of SetLocked.
func (mr *MockUserMockRecorder) SetLocked(until, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLocked", reflect.TypeOf((*MockUser)(nil).SetLocked), until, reason)
}

// SetLogins mocks base method.
func (m *MockUser) SetLogins(logins []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogins", logins)
}

// SetLogins indicates an expected call of SetLogins.
func (mr *MockUserMockRecorder) SetLogins(logins any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogins", reflect.TypeOf((*MockUser)(nil).SetLogins), logins)
}

// SetMetadata mocks base method.
func (m *MockUser) SetMetadata(meta types.Metadata) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMetadata", meta)
}

// SetMetadata indicates an expected call of SetMetadata.
func (mr *MockUserMockRecorder) SetMetadata(meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetadata", reflect.TypeOf((*MockUser)(nil).SetMetadata), meta)
}

// SetName mocks base method.
func (m *MockUser) SetName(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetName", arg0)
}

// SetName indicates an expected call of SetName.
func (mr *MockUserMockRecorder) SetName(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetName", reflect.TypeOf((*MockUser)(nil).SetName), arg0)
}

// SetOrigin mocks base method.
func (m *MockUser) SetOrigin(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOrigin", arg0)
}

// SetOrigin indicates an expected call of SetOrigin.
func (mr *MockUserMockRecorder) SetOrigin(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrigin", reflect.TypeOf((*MockUser)(nil).SetOrigin), arg0)
}

// SetPasswordState mocks base method.
func (m *MockUser) SetPasswordState(arg0 types.PasswordState) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPasswordState", arg0)
}

// SetPasswordState indicates an expected call of SetPasswordState.
func (mr *MockUserMockRecorder) SetPasswordState(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPasswordState", reflect.TypeOf((*MockUser)(nil).SetPasswordState), arg0)
}

// SetRevision mocks base method.
func (m *MockUser) SetRevision(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRevision", arg0)
}

// SetRevision indicates an expected call of SetRevision.
func (mr *MockUserMockRecorder) SetRevision(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRevision", reflect.TypeOf((*MockUser)(nil).SetRevision), arg0)
}

// SetRoles mocks base method.
func (m *MockUser) SetRoles(roles []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRoles", roles)
}

// SetRoles indicates an expected call of SetRoles.
func (mr *MockUserMockRecorder) SetRoles(roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoles", reflect.TypeOf((*MockUser)(nil).SetRoles), roles)
}

// SetStaticLabels mocks base method.
func (m *MockUser) SetStaticLabels(sl map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStaticLabels", sl)
}

// SetStaticLabels indicates an expected call of SetStaticLabels.
func (mr *MockUserMockRecorder) SetStaticLabels(sl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStaticLabels", reflect.TypeOf((*MockUser)(nil).SetStaticLabels), sl)
}

// SetSubKind mocks base method.
func (m *MockUser) SetSubKind(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSubKind", arg0)
}

// SetSubKind indicates an expected call of SetSubKind.
func (mr *MockUserMockRecorder) SetSubKind(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSubKind", reflect.TypeOf((*MockUser)(nil).SetSubKind), arg0)
}

// SetTraits mocks base method.
func (m *MockUser) SetTraits(arg0 map[string][]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTraits", arg0)
}

// SetTraits indicates an expected call of SetTraits.
func (mr *MockUserMockRecorder) SetTraits(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTraits", reflect.TypeOf((*MockUser)(nil).SetTraits), arg0)
}

// SetTrustedDeviceIDs mocks base method.
func (m *MockUser) SetTrustedDeviceIDs(ids []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrustedDeviceIDs", ids)
}

// SetTrustedDeviceIDs indicates an expected call of SetTrustedDeviceIDs.
func (mr *MockUserMockRecorder) SetTrustedDeviceIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrustedDeviceIDs", reflect.TypeOf((*MockUser)(nil).SetTrustedDeviceIDs), ids)
}

// SetWeakestDevice mocks base method.
func (m *MockUser) SetWeakestDevice(arg0 types.MFADeviceKind) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetWeakestDevice", arg0)
}

// SetWeakestDevice indicates an expected call of SetWeakestDevice.
func (mr *MockUserMockRecorder) SetWeakestDevice(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWeakestDevice", reflect.TypeOf((*MockUser)(nil).SetWeakestDevice), arg0)
}

// SetWindowsLogins mocks base method.
func (m *MockUser) SetWindowsLogins(logins []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetWindowsLogins", logins)
}

// SetWindowsLogins indicates an expected call of SetWindowsLogins.
func (mr *MockUserMockRecorder) SetWindowsLogins(logins any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWindowsLogins", reflect.TypeOf((*MockUser)(nil).SetWindowsLogins), logins)
}

// String mocks base method.
func (m *MockUser) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockUserMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockUser)(nil).String))
}

// WithoutSecrets mocks base method.
func (m *MockUser) WithoutSecrets() types.Resource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithoutSecrets")
	ret0, _ := ret[0].(types.Resource)
	return ret0
}

// WithoutSecrets indicates an expected call of WithoutSecrets.
func (mr *MockUserMockRecorder) WithoutSecrets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithoutSecrets", reflect.TypeOf((*MockUser)(nil).WithoutSecrets))
}
