name: PRD CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 최신 버전 사용

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 최신 버전 사용

      - name: Cache Docker layers
        uses: actions/cache@v3  # 최신 버전 사용
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1  # 최신 버전 사용
        with:
          credentials_json: ${{ secrets.ORG_PRD_GCP_CREDENTIALS }}

      - name: Configure docker for gcloud
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker buildx build --push \
            --tag asia-northeast3-docker.pkg.dev/${{ secrets.ORG_PRD_GCP_PROJECT_ID }}/${{ secrets.ORG_PRD_GCP_REGISTRY_NAME }}/teleport-plugin-slack-access-request:${{ github.sha }}${{ github.run_attempt }} .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout deployment repo
        uses: actions/checkout@v3  # 최신 버전 사용
        with:
          repository: teletwoboy/teletwoboy-manifest
          path: manifests
          token: ${{ secrets.ORG_GITHUB_KEY }}

      - name: Update manifest
        run: |
          sed -i "s|image: .*|image: asia-northeast3-docker.pkg.dev/${{ secrets.ORG_PRD_GCP_PROJECT_ID }}/${{ secrets.ORG_PRD_GCP_REGISTRY_NAME }}/teleport-plugin-slack-access-request:${{ github.sha }}${{ github.run_attempt }}|" manifests/prd/teleport-plugin-slack-access-request/deployment.yaml

      - name: Commit and push changes
        working-directory: manifests
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update image to asia-northeast3-docker.pkg.dev/${{ secrets.ORG_PRD_GCP_PROJECT_ID }}/${{ secrets.ORG_PRD_GCP_REGISTRY_NAME }}/teleport-plugin-slack-access-request:${{ github.sha }}${{ github.run_attempt }}"
          git push

  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always()
    steps:
      - name: Send Discord Notification
        run: |
          if [ "${{ needs.build.result }}" == "success" ] && [ "${{ needs.deploy.result }}" == "success" ]; then
            STATUS="✅ 배포 성공"
          else
            STATUS="❌ 배포 실패"
          fi
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"content\": \"${STATUS} \n\
              \`1. Repository\`: \`${{ github.repository }}\`\n\
              \`2. Run Branch\`: \`prd\`\n\
              \`3. Run Attempt\`: \`${{ github.run_attempt }}\`\n\
              \`4. Commit\`: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}>\"
              }" \
              ${{ secrets.ORG_PRD_DISCORD_WEBHOOK_URL }}