name: lint-dev-pr.yml
on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.2.1

      - name: Run golangci-lint
        run: |
          $(go env GOPATH)/bin/golangci-lint run --timeout=5m

  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [lint]
    if: always()
    steps:
      - name: Send Discord Notification
        run: |
          if [ "${{ needs.lint.result }}" == "success" ]; then
            STATUS="✅ lint Success"
          else
            STATUS="❌ lint Fail"
          fi
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"content\": \"${STATUS} \n\
              \`1. Repository\`: \`${{ github.repository }}\`\n\
              \`2. Run Branch\`: \`${{ github.head_ref }}\`\n\
              \`3. Run Attempt\`: \`${{ github.run_attempt }}\`\n\
              \`4. Commit\`: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}>\"
              }" \
              ${{ secrets.ORG_DEV_PR_DISCORD_WEBHOOK_URL }}